<a href="https://colab.research.google.com/github/Grace-Gitome/DS_Track/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Source: Python Data Science Handbook by Jake Vanders
#Numpy is short for Numerical python.

### Understanding data types in python

Python is easy to use due to dynamic typing <br>

In statically-typed languages like C or Jave each variable is explicity declared.<br>

```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

In python the data types are dynamically inferred meaning we can assign any data to any variable.<br>

```python
# Python code
result = 0
for i in range(100):
  result += i

```

In [5]:
#List of integers.
L= list(range(10))
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L)


list

In [8]:
type(L[0])

int

In [10]:
#List of strings
L2 = [str(c) for c in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [11]:
type(L2[0])

str

In [12]:
#heterogeneous strring
L3 = [True, "2", 3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [14]:
#Python list is that each item in the lit must contain its own type info,reference etc resultng to redundancy.
#fixed-type(Numpy-style) array contains a single pointer to each block of data. It is much for efficient in storing and manipulating data.

In [16]:
#Fixed array in python

import array
L = list(range(10))
A = array.array('i',L)  # i is a typecode indicating contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating arrays from lists

In [18]:
#Creating array from python lists
import numpy as np
np.array([1,2,3,4,5])

#unlike python lists, Numpy is constrained to arrays that contain the same type.

array([1, 2, 3, 4, 5])

In [19]:
#if datatypes dont match,Numpy will upcast
np.array([1,2,3,4.7,5])

array([1. , 2. , 3. , 4.7, 5. ])

In [20]:
#setting the data type use dtype
np.array([1,2,3,4,5], dtype = 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [21]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]]) #inner list are treated as rows

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch using Numpy

In [22]:
#Creating arrays from scratch
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones(6, dtype = int)

array([1, 1, 1, 1, 1, 1])

In [25]:
#3x5 floating array
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#filled with 7
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [29]:
#an array filled with a linear sequence
#arange() function
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
#an array of 6 values that are evely spaced between 0 and 1
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
#3x3 uniformly distributed matrix
np.random.random((3,3))

array([[0.86855642, 0.36223354, 0.63583489],
       [0.59142507, 0.19945668, 0.63726193],
       [0.49246362, 0.82741902, 0.60743784]])

In [40]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal (0,1 ,(3,3))

array([[ 0.27045742, -1.72160056, -1.41415948],
       [ 0.28856881,  0.83491786, -0.37570108],
       [ 0.16082327, -1.04877146,  1.1162039 ]])

In [42]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[0, 2, 2],
       [4, 4, 0],
       [3, 9, 9]])

In [43]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Data Types

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

#The Basics of Numpy Arrays

#### Numpy array attributes
