<a href="https://colab.research.google.com/github/Grace-Gitome/DS_Track/blob/main/Introduction_to_Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Getting started with Python & Data Analysis
Data science pipleline can be described as an end-to-end process in which every step contributes to the final insights. <br>
Step 1: Data scooping <br>
Collection of data from various sources i.e downloading from internet, questionnaires and surveys. <br>

Step 2: Data review <br>
Data wrangling, reviewing and transforming data from a messy form into a more appropriate state for ease of use.<br>

Step 3: Feature engineering <br>
Conducting Exploratory Data Analysis (EDA) on the cleaned data using visualizations and statistical methods. <br>

Step 4: Feature review <br>
Step 5 Model selection and review <br>
Modelling involves using statistical and ML methods for classifying and clustering the processed data to create predictive modles.

Step 6: Model evaluation and insights <br>
Several evaluation methods are employed to compare the performance of these moels and continuously improve before a final model is selected.<br>

Step 7: Interaction/production <br>
Presentation of finding from analysis through visualisations and clear reporting.<br>

Step 8: Feedback <br>
This is an iterative process

### Numpy array and vectorization
NumPy - Numeric Python Library. It is the backbone of all kinds of scientific and numeric computing in python. <br>

Pandas - toolkit inbuild in NumPy with datastructures called dataframes.  It helps in analysis and data manipulation<br>

In [ ]:
#Numpys main data type is ndarray
#ndarray can be defines as the collection of the data type (dtype) objects.

In [134]:
#1 dimensional array is a scalar
import numpy as  np
a1 = np.array ([1,2,3])
a1


array([1, 2, 3])

In [136]:
#2 dimentional array is known as a vector
a2 =np.array([[1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 3 dimensional array is know as a matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,25],
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 25],
        [16, 17, 18]]])

In [35]:
print(a1.shape)  #(row,colum)

print(a2.shape)

print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [37]:
#checking dimension (scalar,vector,matrix)

print(a1.ndim)

print(a2.ndim)

print(a3.ndim)


1
2
3


In [38]:
#the number of values in the array
print(a1.size)

print(a2.size)

print(a3.size)


3
6
18


In [39]:
from numpy.core.shape_base import atleast_2d
#checking dimension
print(type(a1))

print(type(a2))

print(type(a3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [41]:
#checking data type

print(a1.dtype)


print(a2.dtype)


print(a3.dtype)

int64
int64
int64


In [83]:
a1

sum(a1)

6

In [54]:
import numpy as np

arr = [6,7,8,9]
print(type(arr))   #type() function  indicates the object type

a = np.array(arr)
print(a.shape)      #indicates number of items in the array (row,column)

print(a.dtype)

print(a.ndim)       #indicates the dimension of the array

<class 'list'>
(4,)
int64
1


In [55]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) 

print(b)

print(b.ndim) #array dimension

print(b.shape) # (row,column) =(2,3)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [43]:
import numpy as np

#There are some inbuild functions that can be used to initialize numpy

np.random.random((2,3))



array([[0.03719166, 0.70708443, 0.40860238],
       [0.82485603, 0.00714028, 0.91641302]])

In [52]:
np.random.randint(-1,10, size = (7,4) ) # random integers between -1 and 10

array([[ 6,  5,  6, -1],
       [ 1,  1,  1,  4],
       [-1,  3, -1,  7],
       [ 5,  6, -1,  6],
       [ 4,  4,  0,  7],
       [ 0,  4,  4,  0],
       [ 1,  8,  2, -1]])

In [53]:
import numpy as numpy

np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
import numpy as np

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((5,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
import numpy as np

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#set random seed to 0
np.random.seed(1)

#make an array with random integer numbers

np.random.randint(1,10,size = (3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [99]:
np.random.seed(2)

a= np.random.randint(2,8, (3,3))

a

array([[2, 7, 2],
       [5, 4, 5],
       [2, 4, 3]])

In [101]:
print(np.sum(a))

print(np.max(a))

print(a.T )#transpose

34
7
[[2 5 2]
 [7 4 4]
 [2 5 3]]


Interoperability of arrays and scalars <br>
Vector - an object that has both magnitude and direction <br>

Scalar - a physical quanitity that is completely described by its magnitude <br>

Vectorisation in numpy arrays allows for faster processing by eliminating loops while dealing with arrays of equal shape.

In [ ]:
import numpy as np

c=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
d=np.array([[7.0,8.0,9.0],[10.0,11.0,12.0]])

print(c+d)

print(c**2) #pow 2

[[ 8. 10. 12.]
 [14. 16. 18.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

#slicing array
print (e[:3,:2] )

 

[[10 11]
 [13 14]
 [16 17]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [80]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

print( e[e>15])

[16 17 18 19 20 21]


### Introducing Pandas data structures: Series, dataFrames and Index objects

Pandas
It has two main datatypes, Series and DataFrame

Series - 1 dimensional column
Dataframe - 2 dimensional table with rows and columns

Seriees are creating by the command pd.Series() and passing it a python list.

Dataframes are created usinf pd.DataFrame() and passing it a python dictionary

SERIES

One dimensional array with homogeneous elements of different types.

In [79]:
#creating a series from pd array
import pandas as pd
import numpy as np
ourSeries = pd.Series(np.random.randint(3,7, size=(3,)))
print(ourSeries)

0    3
1    4
2    3
dtype: int64


In [156]:
import pandas as pd

#Creating a series of car types
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [157]:
#creatig a series of colors.
colors =pd.Series(["Blue","Red","White"])
colors

0     Blue
1      Red
2    White
dtype: object

In [159]:
#creating a dataframe of cars and colors
carData = pd.DataFrame({" CarType": cars,
                        "Color"   : colors    
                      })
carData

CarType  Color
0      BMW   Blue
1   Toyota    Red
2    Honda  White

In [2]:
#importing data
from google.colab import files

uploaded = files.upload()

Saving cars.csv to cars.csv


In [22]:
import io
import pandas as pd
cars = pd.read_csv(io.BytesIO(uploaded['cars.csv']))
cars
#cars.head() shows the first five rows

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [10]:
#data types
cars.dtypes

Unnamed: 0     object
mpg           float64
cyl             int64
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs              int64
am              int64
gear            int64
carb            int64
dtype: object

In [12]:
cars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [14]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
 11  carb        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [16]:
cars.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [18]:
cars.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [19]:
carColumns = cars.columns
carColumns[2]

'cyl'

In [20]:
cars.index

RangeIndex(start=0, stop=32, step=1)

In [21]:
#length of dataframe
len(cars)

32

In [23]:
#view first five rows
cars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [24]:
#view first 3 rows
cars.head(3)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0      Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1  Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2     Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

   carb  
0     4  
1     4  
2     1

In [25]:
#view last 5 rows
cars.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [27]:
#view last three rows
cars.tail(3)

Unnamed: 0   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29   Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
31     Volvo 142E  21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [65]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [66]:
#creating series with numpy array
import numpy as np
import pandas as pd

DaysList = np.array (["Monday","Tuesday","Wednesday"])
NumpyDays = pd.Series(DaysList)
print(NumpyDays)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [67]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])

print(days[0])

print(days[1:])




Monday
1      Tuesday
2    Wednesday
dtype: object


*DATA* FRAMES

can be described as a table (2 dimensions) <br>
It is made up of many series with the same index

In [74]:
#Creating a datafrom from a ndarry //numpy array
import numpy as np
import pandas as pd
dataFrame = pd.DataFrame(np.random.randint(0,6, size=(2,2)))
dataFrame

0  1
0  1  1
1  0  5

In [107]:
#creating an ndarry with random values
np.random.seed(0)
salesAmount = np.random.randint(0,20, size =(5,3))
salesAmount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [109]:
#creating a weekly sales dataFrame from the ndarray

weeklySales =pd.DataFrame(salesAmount, 
                          index = ["Mon","Tue","Wed","Thur","Fri"],
                          columns =["Almond Butter", "Peanut Butter","Cashew Butter"]
                          )
weeklySales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [132]:
#prices array
prices = np.array([10,8,12])
prices


array([10,  8, 12])

In [133]:
#create butter prices Dataframe
butterPrices = pd.DataFrame(prices.reshape(1,3),
                            index = ["Price"],
                            columns= ["Almond Butter", "Peanut Butter","Cashew Butter"]
                            )
butterPrices



Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [144]:
#total sales
totalSales = prices.dot(salesAmount.T)
totalSales

array([240, 138, 458, 232, 142])

In [155]:
#daily sales
print(butterPrices)

print("\n")

print(weeklySales)

print("\n")

dailySales =butterPrices.dot(weeklySales.T)
print(dailySales)
print("\n")

weeklySales["Total ($)"] = dailySales.T #adding a column for the total sales per day
weeklySales

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12


      Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7


       Mon  Tue  Wed  Thur  Fri
Price  240  138  458   232  142




Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon              12             15              0        240
Tue               3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142

In [68]:
import numpy as np
import pandas as pd

print(pd.DataFrame())   #print empty dataframe

Empty DataFrame
Columns: []
Index: []


In [30]:
#create dataframe from a dictionary
import numpy as np
import pandas as pd
df_dict = {"Country":["Ghana", "Kenya", "Nigeria", "Togo"],
           "Capital":["Accra","Nairobi","Abuja","Lome"],
           "Population":[10000, 8500, 35000, 12000],
           "Age":[60,70,80,90]
           }
df = pd.DataFrame(df_dict, index = [2,4,6,8] )

print(df)


   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [31]:
#creating dataframe from list

import numpy as np
import pandas as np

df_list = [["Ghana", "Accra", 10000,60],
           ["Kenya", "Nairobi", 8500,70],
           ["Nigeria", "Abuja", 35000, 80],
           ["Togo","Lome", 12000,90]]
df1 = pd.DataFrame(df_list, columns = ["Country","Capital","Population","Age"], index = [2,4,6,8] )

print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [ ]:
#retreiving data in dataframes using iat,iloc and loc accessors.

In [32]:
#iloc selects values from the rows and columns using integer index to locate position

df.iloc[3] 

Country        Togo
Capital        Lome
Population    12000
Age              90
Name: 8, dtype: object

In [33]:
#loc selects rows or columns using labels.
#used when refering to position
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [ ]:
#select the capital column
df["Capital"]

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [34]:
#Boolean indexing

#Select capitals with population greater that 85000
df[df["Population"]>8500]

Country Capital  Population  Age
2    Ghana   Accra       10000   60
6  Nigeria   Abuja       35000   80
8     Togo    Lome       12000   90

In [ ]:
#at at iat retreive single values values.
#at uses column and row labels.
#iat uses indices.
df.at[6,"Capital"] 

'Abuja'

In [ ]:
df.iat[2,0]

'Nigeria'

In [ ]:
df.iat[3,0]

'Togo'

In [ ]:
#In colclusion:
#iloc - uses index to select values from row & column.
#loc - uses label to select values from row & column.
#at - uses labels on row and column to retreive a single value.
#iat - uses indices on row and column  to retreive a value.

In [ ]:
#descriptive statistics functions.
print (df.mean())

Population    16375.0
Age              75.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [ ]:
print(df.describe())

         Population        Age
count      4.000000   4.000000
mean   16375.000000  75.000000
std    12499.166639  12.909944
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  75.000000
75%    17750.000000  82.500000
max    35000.000000  90.000000


In [ ]:
print (df['Population'].sum())

65500


In [ ]:
#Pandas represent missing values as NA or NaN

#which can be:

#filled - fillna(), replace()
#removed - dropna()
#detected - isnull()  notnull()
