<a href="https://colab.research.google.com/github/Grace-Gitome/DS_Track/blob/main/Introduction_to_Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Getting started with Python & Data Analysis
Data science pipleline can be described as an end-to-end process in which every step contributes to the final insights. <br>
Step 1: Data scooping <br>
Collection of data from various sources i.e downloading from internet, questionnaires and surveys. <br>

Step 2: Data review <br>
Data wrangling, reviewing and transforming data from a messy form into a more appropriate state for ease of use.<br>

Step 3: Feature engineering <br>
Conducting Exploratory Data Analysis (EDA) on the cleaned data using visualizations and statistical methods. <br>

Step 4: Feature review <br>
Step 5 Model selection and review <br>
Modelling involves using statistical and ML methods for classifying and clustering the processed data to create predictive modles.

Step 6: Model evaluation and insights <br>
Several evaluation methods are employed to compare the performance of these moels and continuously improve before a final model is selected.<br>

Step 7: Interaction/production <br>
Presentation of finding from analysis through visualisations and clear reporting.<br>

Step 8: Feedback <br>
This is an iterative process

### Numpy array and vectorization
NumPy - Numeric Python Library <br>
Pandas - toolkit inbuild in NumPy with datastructures called dataframes.<br>

In [ ]:
import numpy as np

arr = [6,7,8,9]
print(type(arr))   #type() function  indicates the object type

a = np.array(arr)
print(a.shape)      #indicates number of items in the array (row,column)

print(a.dtype)

print(a.ndim)       #indicates the dimension of the array

<class 'list'>
(4,)
int64
1


In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) 

print(b)

print(b.ndim) #array dimension

print(b.shape) # (row,column) =(2,3)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
import numpy as np

#There are some inbuild functions that can be used to initialize numpy

np.random.random((2,3))



array([[0.34183446, 0.65520718, 0.63396355],
       [0.5341236 , 0.26290275, 0.19144274]])

In [ ]:
import numpy as numpy

np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Interoperability of arrays and scalars <br>
Vector - an object that has both magnitude and direction <br>

Scalar - a physical quanitity that is completely described by its magnitude <br>

Vectorisation in numpy arrays allows for faster processing by eliminating loops while dealing with arrays of equal shape.

In [ ]:
import numpy as np

c=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
d=np.array([[7.0,8.0,9.0],[10.0,11.0,12.0]])

print(c+d)

print(c**2) #pow 2

[[ 8. 10. 12.]
 [14. 16. 18.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

#slicing array
print (e[:3,:2] )

 

[[10 11]
 [13 14]
 [16 17]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [ ]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

print( e[e>15])

[16 17 18 19 20 21]


### Introducing Pandas data structures: Series, dataFrames and Index objects



SERIES

One dimensional array with homogeneous elements of different types.

In [ ]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [ ]:
#creating series with numpy array
import numpy as np
import pandas as pd

DaysList = np.array (["Monday","Tuesday","Wednesday"])
NumpyDays = pd.Series(DaysList)
print(NumpyDays)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [ ]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])

print(days[0])

print(days[1:])




Monday
1      Tuesday
2    Wednesday
dtype: object


DATA FRAMES

can be described as a table (2 dimensions) <br>
It is made up of many series with the same index

In [3]:
import numpy as np
import pandas as pd

print(pd.DataFrame())   #print empty dataframe

Empty DataFrame
Columns: []
Index: []


In [6]:
#create datafrme from a dictionary
import numpy as np
import pandas as pd
df_dict = {"Country":["Ghana", "Kenya", "Nigeria", "Togo"],
           "Capital":["Accra","Nairobi","Abuja","Lome"],
           "Population":[10000, 8500, 35000, 12000],
           "Age":[60,70,80,90]
           }
df = pd.DataFrame(df_dict, index = [2,4,6,8] )

print(df)


   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [10]:
#creating dataframe from list

import numpy as np
import pandas as np

df_list = [["Ghana", "Accra", 10000,60],
           ["Kenya", "Nairobi", 8500,70],
           ["Nigeria", "Abuja", 35000, 80],
           ["Togo","Lome", 12000,90]]
df1 = pd.DataFrame(df_list, columns = ["Country","Capital","Population","Age"], index = [2,4,6,8] )

print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [ ]:
#retreiving data in dataframes using iat,iloc and loc accessors.

In [12]:
#iloc selects values from the rows and columns using integer index to locate position

df.iloc[3] 

Country        Togo
Capital        Lome
Population    12000
Age              90
Name: 8, dtype: object

In [13]:
#loc selects rows or columns using labels.
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [14]:
#select the capital column
df["Capital"]

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [16]:
#at at iat retreive single values values.
#at uses column and row labels.
#iat uses indices.
df.at[6,"Capital"] 

'Abuja'

In [17]:
df.iat[2,0]

'Nigeria'

In [19]:
df.iat[3,0]

'Togo'