<a href="https://colab.research.google.com/github/Grace-Gitome/DS_Track/blob/main/Introduction_to_Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Getting started with Python & Data Analysis
Data science pipleline can be described as an end-to-end process in which every step contributes to the final insights. <br>
Step 1: Data scooping <br>
Collection of data from various sources i.e downloading from internet, questionnaires and surveys. <br>

Step 2: Data review <br>
Data wrangling, reviewing and transforming data from a messy form into a more appropriate state for ease of use.<br>

Step 3: Feature engineering <br>
Conducting Exploratory Data Analysis (EDA) on the cleaned data using visualizations and statistical methods. <br>

Step 4: Feature review <br>
Step 5 Model selection and review <br>
Modelling involves using statistical and ML methods for classifying and clustering the processed data to create predictive modles.

Step 6: Model evaluation and insights <br>
Several evaluation methods are employed to compare the performance of these moels and continuously improve before a final model is selected.<br>

Step 7: Interaction/production <br>
Presentation of finding from analysis through visualisations and clear reporting.<br>

Step 8: Feedback <br>
This is an iterative process

### Numpy array and vectorization
NumPy - Numeric Python Library. It is the backbone of all kinds of scientific and numeric computing in python. <br>

Pandas - toolkit inbuild in NumPy with datastructures called dataframes.  It helps in analysis and data manipulation<br>

In [ ]:
#Numpys main data type is ndarray
#ndarray can be defines as the collection of the data type (dtype) objects.

In [129]:
#1 dimensional array is a scalar
import numpy as  np
a1 = np.array ([1,2,3])
a1
a1

array([1, 2, 3])

In [128]:
#2 dimentional array is known as a vector
a2 =np.array([[1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 3 dimensional array is know as a matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,25],
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 25],
        [16, 17, 18]]])

In [35]:
print(a1.shape)  #(row,colum)

print(a2.shape)

print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [37]:
#checking dimension (scalar,vector,matrix)

print(a1.ndim)

print(a2.ndim)

print(a3.ndim)


1
2
3


In [38]:
#the number of values in the array
print(a1.size)

print(a2.size)

print(a3.size)


3
6
18


In [39]:
from numpy.core.shape_base import atleast_2d
#checking dimension
print(type(a1))

print(type(a2))

print(type(a3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [41]:
#checking data type

print(a1.dtype)


print(a2.dtype)


print(a3.dtype)

int64
int64
int64


In [83]:
a1

sum(a1)

6

In [54]:
import numpy as np

arr = [6,7,8,9]
print(type(arr))   #type() function  indicates the object type

a = np.array(arr)
print(a.shape)      #indicates number of items in the array (row,column)

print(a.dtype)

print(a.ndim)       #indicates the dimension of the array

<class 'list'>
(4,)
int64
1


In [55]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) 

print(b)

print(b.ndim) #array dimension

print(b.shape) # (row,column) =(2,3)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [43]:
import numpy as np

#There are some inbuild functions that can be used to initialize numpy

np.random.random((2,3))



array([[0.03719166, 0.70708443, 0.40860238],
       [0.82485603, 0.00714028, 0.91641302]])

In [52]:
np.random.randint(-1,10, size = (7,4) ) # random integers between -1 and 10

array([[ 6,  5,  6, -1],
       [ 1,  1,  1,  4],
       [-1,  3, -1,  7],
       [ 5,  6, -1,  6],
       [ 4,  4,  0,  7],
       [ 0,  4,  4,  0],
       [ 1,  8,  2, -1]])

In [53]:
import numpy as numpy

np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
import numpy as np

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((5,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
import numpy as np

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#set random seed to 0
np.random.seed(1)

#make an array with random integer numbers

np.random.randint(1,10,size = (3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [99]:
np.random.seed(2)

a= np.random.randint(2,8, (3,3))

a

array([[2, 7, 2],
       [5, 4, 5],
       [2, 4, 3]])

In [101]:
print(np.sum(a))

print(np.max(a))

print(a.T )#transpose

34
7
[[2 5 2]
 [7 4 4]
 [2 5 3]]


Interoperability of arrays and scalars <br>
Vector - an object that has both magnitude and direction <br>

Scalar - a physical quanitity that is completely described by its magnitude <br>

Vectorisation in numpy arrays allows for faster processing by eliminating loops while dealing with arrays of equal shape.

In [ ]:
import numpy as np

c=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
d=np.array([[7.0,8.0,9.0],[10.0,11.0,12.0]])

print(c+d)

print(c**2) #pow 2

[[ 8. 10. 12.]
 [14. 16. 18.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

#slicing array
print (e[:3,:2] )

 

[[10 11]
 [13 14]
 [16 17]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [80]:
import numpy as np

e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

print( e[e>15])

[16 17 18 19 20 21]


### Introducing Pandas data structures: Series, dataFrames and Index objects



SERIES

One dimensional array with homogeneous elements of different types.

In [79]:
#creating a series from pd array
import pandas as pd
import numpy as np
ourSeries = pd.Series(np.random.randint(3,7, size=(3,)))
print(ourSeries)

0    3
1    4
2    3
dtype: int64


In [65]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [66]:
#creating series with numpy array
import numpy as np
import pandas as pd

DaysList = np.array (["Monday","Tuesday","Wednesday"])
NumpyDays = pd.Series(DaysList)
print(NumpyDays)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [67]:
import pandas as pd
days = pd.Series(["Monday","Tuesday","Wednesday"])

print(days[0])

print(days[1:])




Monday
1      Tuesday
2    Wednesday
dtype: object


DATA FRAMES

can be described as a table (2 dimensions) <br>
It is made up of many series with the same index

In [74]:
#Creating a datafrom from a ndarry //numpy array
import numpy as np
import pandas as pd
dataFrame = pd.DataFrame(np.random.randint(0,6, size=(2,2)))
dataFrame

0  1
0  1  1
1  0  5

In [107]:
#creating an ndarry with random values
np.random.seed(0)
salesAmount = np.random.randint(0,20, size =(5,3))
salesAmount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [109]:
#creating a weekly sales dataFrame from the ndarray

weeklySales =pd.DataFrame(salesAmount, 
                          index = ["Mon","Tue","Wed","Thur","Fri"],
                          columns =["Almond Butter", "Peanut Butter","Cashew Butter"]
                          )
weeklySales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [125]:
#prices array
prices = np.array([10,8,12])
prices
prices.shape

(3,)

In [122]:
#create butter prices Dataframe
butterPrices = pd.DataFrame(prices.reshape(1,3),
                            index = ["Price"],
                            columns= ["Almond Butter", "Peanut Butter","Cashew Butter"]
                            )
butterPrices



Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [120]:
#total sales
totalSales = prices.dot(salesAmount)

ValueError: ignored

In [68]:
import numpy as np
import pandas as pd

print(pd.DataFrame())   #print empty dataframe

Empty DataFrame
Columns: []
Index: []


In [ ]:
#create dataframe from a dictionary
import numpy as np
import pandas as pd
df_dict = {"Country":["Ghana", "Kenya", "Nigeria", "Togo"],
           "Capital":["Accra","Nairobi","Abuja","Lome"],
           "Population":[10000, 8500, 35000, 12000],
           "Age":[60,70,80,90]
           }
df = pd.DataFrame(df_dict, index = [2,4,6,8] )

print(df)


   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [ ]:
#creating dataframe from list

import numpy as np
import pandas as np

df_list = [["Ghana", "Accra", 10000,60],
           ["Kenya", "Nairobi", 8500,70],
           ["Nigeria", "Abuja", 35000, 80],
           ["Togo","Lome", 12000,90]]
df1 = pd.DataFrame(df_list, columns = ["Country","Capital","Population","Age"], index = [2,4,6,8] )

print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   90


In [ ]:
#retreiving data in dataframes using iat,iloc and loc accessors.

In [ ]:
#iloc selects values from the rows and columns using integer index to locate position

df.iloc[3] 

Country        Togo
Capital        Lome
Population    12000
Age              90
Name: 8, dtype: object

In [ ]:
#loc selects rows or columns using labels.
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [ ]:
#select the capital column
df["Capital"]

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [ ]:
#at at iat retreive single values values.
#at uses column and row labels.
#iat uses indices.
df.at[6,"Capital"] 

'Abuja'

In [ ]:
df.iat[2,0]

'Nigeria'

In [ ]:
df.iat[3,0]

'Togo'

In [ ]:
#In colclusion:
#iloc - uses index to select values from row & column.
#loc - uses label to select values from row & column.
#at - uses labels on row and column to retreive a single value.
#iat - uses indices on row and column to retreive a value.

In [ ]:
#descriptive statistics functions.
print (df.mean())

Population    16375.0
Age              75.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [ ]:
print(df.describe())

         Population        Age
count      4.000000   4.000000
mean   16375.000000  75.000000
std    12499.166639  12.909944
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  75.000000
75%    17750.000000  82.500000
max    35000.000000  90.000000


In [ ]:
print (df['Population'].sum())

65500


In [ ]:
#Pandas represent missing values as NA or NaN

#which can be:

#filled - fillna(), replace()
#removed - dropna()
#detected - isnull()  notnull()
