<a href="https://colab.research.google.com/github/Grace-Gitome/DS_Track/blob/main/Stage_A_assesment_ipynp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving FoodBalanceSheets_E_Africa_NOFLAG.csv to FoodBalanceSheets_E_Africa_NOFLAG.csv


### Question 1
Given the following numpy array

                array =([[94, *89, *63],
                        [93, *92, *48],
                        [92, 94, 56]])
How would you select the elements in bold and italics from the array?

Options

1. array[ : 2, 0 : ]
2. array[ : 2, 1 : ] 
3. array[ 1 : , : ]
4. array[ : 1, 1 : ]
5. array[ : 1, 1 :]

#### Solution

In [6]:
#The concept of the question involves slicing an array.
array = np.array([[94, 89, 63],
                [93, 92, 48],
                [92, 94, 56]])

In [10]:
#get the row
array[0:2]

array([[94, 89, 63],
       [93, 92, 48]])

In [12]:
#get the column
array[:,1:3]

array([[89, 63],
       [92, 48],
       [94, 56]])

In [8]:
#array[row_index, col_index]
array [0:2, 1:3]

array([[89, 63],
       [92, 48]])

In [9]:
array[:2, 1:]

array([[89, 63],
       [92, 48]])

In [15]:
array[1,1:3]

array([92, 48])

In [17]:
array[1:,1:3]

array([[92, 48],
       [94, 56]])

In [18]:
array[:1,1:3]

array([[89, 63]])


### Question 2

Answer the following questions based on the African food production dataset provided by the FAO website already provided

What is the total sum of Wine produced in 2015 and 2018 respectively?

Hint:

Perform a groupby sum aggregation on ‘Item’

Options

1. 2134.34 and 3517.22
2. 20675.72 and 26968.27
3. 1584.08 and 1387.21
4. 4251.81 and 4039.32

#### Solution

In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin-1')
df.head(17)


Area Code     Area  Item Code                      Item  Element Code  \
0           4  Algeria       2501                Population           511   
1           4  Algeria       2501                Population          5301   
2           4  Algeria       2901               Grand Total           664   
3           4  Algeria       2901               Grand Total           674   
4           4  Algeria       2901               Grand Total           684   
5           4  Algeria       2903          Vegetal Products           664   
6           4  Algeria       2903          Vegetal Products           674   
7           4  Algeria       2903          Vegetal Products           684   
8           4  Algeria       2941           Animal Products           664   
9           4  Algeria       2941           Animal Products           674   
10          4  Algeria       2941           Animal Products           684   
11          4  Algeria       2905  Cereals - Excluding Beer          5511   
12          4  Algeria       2905  Cereals - Excluding Beer          5611   
13          4  Algeria       2905  Cereals - Excluding Beer          5072   
14          4  Algeria       2905  Cereals - Excluding Beer          5911   
15          4  Algeria       2905  Cereals - Excluding Beer          5301   
16          4  Algeria       2905  Cereals - Excluding Beer          5521   

                                   Element             Unit     Y2014  \
0            Total Population - Both sexes     1000 persons  38924.00   
1                 Domestic supply quantity      1000 tonnes      0.00   
2            Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3   Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4       Fat supply quantity (g/capita/day)     g/capita/day     80.06   
5            Food supply (kcal/capita/day)  kcal/capita/day   2932.00   
6   Protein supply quantity (g/capita/day)     g/capita/day     67.14   
7       Fat supply quantity (g/capita/day)     g/capita/day     53.84   
8            Food supply (kcal/capita/day)  kcal/capita/day    444.00   
9   Protein supply quantity (g/capita/day)     g/capita/day     27.76   
10      Fat supply quantity (g/capita/day)     g/capita/day     26.22   
11                              Production      1000 tonnes   3436.00   
12                         Import Quantity      1000 tonnes  12604.00   
13                         Stock Variation      1000 tonnes    684.00   
14                         Export Quantity      1000 tonnes      3.00   
15                Domestic supply quantity      1000 tonnes  15353.00   
16                                    Feed      1000 tonnes   4725.00   

       Y2015     Y2016     Y2017     Y2018  
0   39728.00  40551.00  41389.00  42228.00  
1       0.00      0.00      0.00      0.00  
2    3379.00   3372.00   3341.00   3322.00  
3      94.35     94.72     92.82     91.83  
4      79.36     77.40     80.19     77.28  
5    2958.00   2941.00   2921.00   2932.00  
6      67.38     67.37     66.11     67.10  
7      54.72     52.04     55.59     54.57  
8     421.00    431.00    421.00    390.00  
9      26.97     27.35     26.71     24.73  
10     24.64     25.37     24.60     22.71  
11   3761.00   3445.00   3478.00   6065.00  
12  13983.00  13523.00  13039.00  13182.00  
13   1663.00    905.00    705.00   2226.00  
14      7.00      7.00     10.00     17.00  
15  16075.00  16056.00  15803.00  17004.00  
16   5070.00   4838.00   4667.00   5266.00

Q2.Total sum of Wine produced in 2015 and 2018 respectively

In [86]:
#perform a groupby sum aggregation Item
Item = df.groupby('Item')['Y2015',"Y2018"].sum()
Item

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  


Y2015      Y2018
Item                                     
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]

In [23]:
Item.loc["Wine"]

Y2015    4251.81
Y2018    4039.32
Name: Wine, dtype: float64

In [87]:
Item.iloc[3]

Y2015    200675.72
Y2018    269648.27
Name: Animal fats, dtype: float64

### Question 3

What is the total Protein supply quantity in Madagascar in 2015?

Options
1. 357.12
2. 180.29
3. 173.05
4. 174.91


In [34]:
madagascarFilter = df[df["Area"] == "Madagascar"]
madagascarFilter 


Area Code        Area  Item Code           Item  Element Code  \
30715        129  Madagascar       2501     Population           511   
30716        129  Madagascar       2501     Population          5301   
30717        129  Madagascar       2901    Grand Total           664   
30718        129  Madagascar       2901    Grand Total           674   
30719        129  Madagascar       2901    Grand Total           684   
...          ...         ...        ...            ...           ...   
32149        129  Madagascar       2899  Miscellaneous          5142   
32150        129  Madagascar       2899  Miscellaneous           645   
32151        129  Madagascar       2899  Miscellaneous           664   
32152        129  Madagascar       2899  Miscellaneous           674   
32153        129  Madagascar       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
30715           Total Population - Both sexes     1000 persons  23590.00   
30716                Domestic supply quantity      1000 tonnes      0.00   
30717           Food supply (kcal/capita/day)  kcal/capita/day   1986.00   
30718  Protein supply quantity (g/capita/day)     g/capita/day     44.45   
30719      Fat supply quantity (g/capita/day)     g/capita/day     22.18   
...                                       ...              ...       ...   
32149                                    Food      1000 tonnes     10.00   
32150     Food supply quantity (kg/capita/yr)               kg      0.44   
32151           Food supply (kcal/capita/day)  kcal/capita/day      0.00   
32152  Protein supply quantity (g/capita/day)     g/capita/day      0.01   
32153      Fat supply quantity (g/capita/day)     g/capita/day      0.01   

          Y2015     Y2016     Y2017     Y2018  
30715  24234.00  24894.00  25571.00  26262.00  
30716      0.00      0.00      0.00      0.00  
30717   1922.00   1918.00   1943.00   1938.00  
30718     43.26     43.35     43.94     44.17  
30719     22.97     23.83     25.26     24.12  
...         ...       ...       ...       ...  
32149     11.00     11.00     11.00     12.00  
32150      0.44      0.44      0.44      0.44  
32151      0.00      0.00      0.00      0.00  
32152      0.01      0.01      0.01      0.01  
32153      0.01      0.01      0.01      0.01  

[1439 rows x 12 columns]

In [37]:
madagascarFilter.groupby(["Element"])["Y2015"].sum()

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.85
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

### Question 4

Which year had the least correlation with ‘Element Code’?

Options
1. 2017
2. 2016
3. 2015
4. 2014

#### Solution

In [39]:
food.corr()["Element Code"]

Area Code      -0.000209
Item Code      -0.024683
Element Code    1.000000
Y2014           0.024457
Y2015           0.023889
Y2016           0.023444
Y2017           0.024254
Y2018           0.024279
Name: Element Code, dtype: float64

### Question 5
Consider the following list of tuples:

y = [(2, 4), (7, 8), (1, 5, 9)]

How would you assign element 8 from the list to a variable x?

Options
1. x = y[1][-1]
2. x = y[2][-1]
3. x = y[1][-2] 
4. x = y[1][1]

#### Solution

In [47]:

y = [(2, 4), (7, 8), (1, 5, 9)]
x = y[1][-1]
print(x)

x = y[1][1]
x

8


8

### Question 7
Perform a groupby operation on ‘Element’.  What is the total number of the sum of Processing in 2017?

Options
1. 292836.00
2. 3231287.75
3. 3947019.23
4. 287134.67
5. 232118.43

#### Solution

In [48]:
df.groupby(["Element"])['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

### Question 12

Given the following python code, what would the output of the code give?

my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

Options
1. Standard Error
2. Type Error
3. Value Error
4. Math Error

#### Solution

In [ ]:
my_tuppy = (1,2,5,8)
my_tuppy[2] =6

TypeError: ignored

### Question 8

What would be the output for?

S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

Options
1. 28
2. 'l'
3. 'i'
4. 'e'

#### Solution

In [49]:
S =[["him","sell"],
    [90,28,43]]

S[0]

['him', 'sell']

In [52]:
S[0][1]

'sell'

In [53]:
S[0][1][1]

'e'

### Question 9

Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the highest sum in 2017?

Options
1. South Africa
2. Ethiopia
3. Egypt
4. Nigeria
5. Kenya

#### Solution

In [58]:
df.groupby(["Area"])["Y2017"].sum().sort_values(ascending =False)[:5]

Area
Nigeria         1483268.23
Egypt            866379.92
South Africa     517590.54
Ethiopia         448683.76
Morocco          388495.36
Name: Y2017, dtype: float64

### Question 10

What is the total number of unique countries in the dataset?

Options
1. 50
2. 45
3. 39
4. 49

#### Solution

In [63]:
df.nunique()["Area"]

49

In [65]:
len(df["Area"].unique())

49

### Question 11

What is the total number and percentage of missing data in 2014 to 3 decimal places?

Options
1. 1538 and 2.522%
2. 1506 and 2.477%
3. 1473 and 2.152 %
4. 1598 and 2.617%
5. 1589 and 2.607%

#### Solution

In [67]:
EmptyValues =df.isnull().sum()
EmptyValues 

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [70]:
y2014 = EmptyValues.loc["Y2014"] 
y2014

1589

In [88]:
EmptyValues.iloc[7] 

1589

In [72]:
Entries = len(df)

In [73]:
(y2014 / Entries ) * 100

2.6073544131401474

### Question 13
If you have the following list

lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = [‘Age’,’Nationality’,’Overall’]

How do you create a pandas DataFrame using this list, to look like the table below?

|  |Age|Nationality| Overall|
|---|---|---|---|
| 1 | 35 | Portugal | 94 |
| 2 | 33 | Argentina | 93 |
| 3 | 30 | Brazil | 92 |

Options
1. pd.Dateframe(lst, column = [‘Age’,’Nationality’,’Overall’], index = [1,2,3])
2. None of the above
3. pd.Dataframe(lst, columns = col, index = [1,2,3])
4. pd.datframe(lst, column = [‘Age’,’Nationality’,’Overall’],index = [1,2,3])
5. pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])

#### Solution


In [74]:
lst = [[35,'Portugal',94],[33,'Argentina',93],[30,'Brazil',92]]
col =['Age','Nationality','Overall']

data = pd.DataFrame(lst,
                    columns = col,
                    index =[1,2,3])
data

Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [75]:
data.iloc[2]

Age                30
Nationality    Brazil
Overall            92
Name: 3, dtype: object

### Question 15

How would you check for the number of rows and columns in a pandas DataFrame named df?

Options
1. df.shape( )
2. pd.length(df)
3. len(df)
4. df.shape

#### Solution

In [80]:
df.shape


(60943, 12)

### Question 14

Perform a groupby operation on ‘Element’.  What year has the highest sum of Stock Variation?

Options
1. 2017
2. 2014
3. 2015
4. 2016

#### Solution

In [96]:
df.groupby("Element")["Y2014","Y2015","Y2016","Y2017"].sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


Y2014       Y2015       Y2016  \
Element                                                                      
Domestic supply quantity                1996716.35  2021493.55  2044842.70   
Export Quantity                          150020.64   157614.47   151920.46   
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77   
Feed                                     216927.89   225050.22   228958.65   
Food                                    1212332.49  1232361.10  1247022.17   
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00   
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28   
Import Quantity                          274144.48   267018.46   286582.78   
Losses                                   153223.00   155439.00   157787.00   
Other uses (non-food)                     78718.13    66254.41    69563.68   
Processing                               282923.00   287929.00   280631.00   
Production                              1931287.75  1947019.39  1943537.15   
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69   
Residuals                                 30149.00    30045.00    37224.00   
Seed                                      21922.92    23976.82    23389.20   
Stock Variation                           58749.83    34910.99    33140.12   
Total Population - Both sexes           1031585.00  1058081.00  1085107.00   
Tourist consumption                         416.00      349.00       89.00   

                                             Y2017  
Element                                             
Domestic supply quantity                2088198.10  
Export Quantity                          182338.80  
Fat supply quantity (g/capita/day)        10253.84  
Feed                                     223705.68  
Food                                    1258888.28  
Food supply (kcal/capita/day)            454681.00  
Food supply quantity (kg/capita/yr)       48690.04  
Import Quantity                          294559.09  
Losses                                   160614.00  
Other uses (non-food)                     91645.97  
Processing                               292836.00  
Production                              2030056.89  
Protein supply quantity (g/capita/day)    11842.45  
Residuals                                 35500.00  
Seed                                      24870.14  
Stock Variation                           54316.91  
Total Population - Both sexes           1112641.00  
Tourist consumption                          91.00

In [99]:
#alternatively
year =df.iloc[:, 7:].columns
year

Index(['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018'], dtype='object')

In [100]:
df.groupby("Element")[year].sum()

Y2014       Y2015       Y2016  \
Element                                                                      
Domestic supply quantity                1996716.35  2021493.55  2044842.70   
Export Quantity                          150020.64   157614.47   151920.46   
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77   
Feed                                     216927.89   225050.22   228958.65   
Food                                    1212332.49  1232361.10  1247022.17   
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00   
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28   
Import Quantity                          274144.48   267018.46   286582.78   
Losses                                   153223.00   155439.00   157787.00   
Other uses (non-food)                     78718.13    66254.41    69563.68   
Processing                               282923.00   287929.00   280631.00   
Production                              1931287.75  1947019.39  1943537.15   
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69   
Residuals                                 30149.00    30045.00    37224.00   
Seed                                      21922.92    23976.82    23389.20   
Stock Variation                           58749.83    34910.99    33140.12   
Total Population - Both sexes           1031585.00  1058081.00  1085107.00   
Tourist consumption                         416.00      349.00       89.00   

                                             Y2017       Y2018  
Element                                                         
Domestic supply quantity                2088198.10  2161192.10  
Export Quantity                          182338.80   181594.80  
Fat supply quantity (g/capita/day)        10253.84    10258.69  
Feed                                     223705.68   233489.68  
Food                                    1258888.28  1303841.28  
Food supply (kcal/capita/day)            454681.00   455261.00  
Food supply quantity (kg/capita/yr)       48690.04    49056.85  
Import Quantity                          294559.09   287997.09  
Losses                                   160614.00   163902.00  
Other uses (non-food)                     91645.97    91300.97  
Processing                               292836.00   308429.00  
Production                              2030056.89  2075072.89  
Protein supply quantity (g/capita/day)    11842.45    11833.56  
Residuals                                 35500.00    34864.00  
Seed                                      24870.14    25263.14  
Stock Variation                           54316.91    20577.91  
Total Population - Both sexes           1112641.00  1140605.00  
Tourist consumption                          91.00       90.00

### Question 16
A pandas Dataframe with dimensions (100,3) has how many features and observations?

Options
1. 100 rows and 3 observations.
2. A pandas dataframe has no attribute feature or observation.
3. 3 features, 100 observations
4. 100 features, 3 observations.

#### Solution

### Question 17
Which of the following dataframe methods can be used to access elements across rows and columns?

Options
1. df.iloc( )
2. c and d
3. df.loc( )
4. df.loc( : )
5. df.iloc[ : ] 

#### Solution

### Question 18
Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the 7th lowest sum in 2017?

Options
1. Comoros
2. Cabo Verde
3. Guinea-Bissau
4. Ghana
5. Seychelles

#### Solution

In [84]:
df.groupby(["Area"])["Y2017"].sum().sort_values(ascending = True)[:9]

Area
Sudan (former)               0.00
Ethiopia PDR                 0.00
Comoros                     59.84
Seychelles                 442.34
Sao Tome and Principe    12662.63
Cabo Verde               14650.74
Guinea-Bissau            19102.77
Lesotho                  21267.96
Botswana                 22101.30
Name: Y2017, dtype: float64

### Question 19
Which of the following is a python inbuilt module?

Options
1. Pandas
2. Matplotlib
3. Math
4. Seaborn

#### Solution

Seaborn is a library for making statistical graphs in Python.<br>
matplotlib - is a python library for visualization.<br>
Pandas is a python library for data analysis and machine learning.<br>
Numpy is a python library for performing high level mathematical operations.<br>
Math - an inbuild module in python for mathematical operations.

### Question 20
What is the mean and standard deviation across the whole dataset for the year 2017 to 2 decimal places?

Options
1. 10.60 and 8.49
2. 140.92 and 1671.86
3. 8.54 and 9876.77
4. 135.23 and 1603.40
5. 10.60 and 17.01

#### Solution

In [85]:
df["Y2017"].describe()

count     59437.000000
mean        140.917765
std        1671.862359
min       -1582.000000
25%           0.000000
50%           0.100000
75%           9.000000
max      190873.000000
Name: Y2017, dtype: float64